CREATE DATABASE IF NOT EXISTS ODATA_SAMPLE;
USE ODATA_SAMPLE;
CREATE TABLE IF NOT EXISTS Manufacturer (
	manufacturerId BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	street VARCHAR(100),
	city VARCHAR(100),
	zipCode VARCHAR(100),
	country VARCHAR(100),
	updated DATE
);

CREATE TABLE IF NOT EXISTS Car (
	carId BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	model VARCHAR(100),
	currency VARCHAR(100),
	price REAL,
	modelYear VARCHAR(100),
	imagePath VARCHAR(100),
	updated DATE,
	manufacturerId BIGINT NOT NULL,
	FOREIGN KEY (manufacturerId) REFERENCES Manufacturer (manufacturerId)
);

CREATE TABLE IF NOT EXISTS users (
  user_name VARCHAR(20) NOT NULL PRIMARY KEY,
  user_pass VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
  role_name VARCHAR(20) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS user_roles(
  user_name VARCHAR(20) NOT NULL,
  role_name VARCHAR(20) NOT NULL,
  PRIMARY KEY (user_name, role_name)
)